// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: zlog_config.proto

package zlog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Format int32

const (
	Format_UNKNOWN Format = 0
	Format_JSON    Format = 1
	Format_CONSOLE Format = 2
)

// Enum value maps for Format.
var (
	Format_name = map[int32]string{
		0: "UNKNOWN",
		1: "JSON",
		2: "CONSOLE",
	}
	Format_value = map[string]int32{
		"UNKNOWN": 0,
		"JSON":    1,
		"CONSOLE": 2,
	}
)

func (x Format) Enum() *Format {
	p := new(Format)
	*p = x
	return p
}

func (x Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Format) Descriptor() protoreflect.EnumDescriptor {
	return file_zlog_config_proto_enumTypes[0].Descriptor()
}

func (Format) Type() protoreflect.EnumType {
	return &file_zlog_config_proto_enumTypes[0]
}

func (x Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Format.Descriptor instead.
func (Format) EnumDescriptor() ([]byte, []int) {
	return file_zlog_config_proto_rawDescGZIP(), []int{0}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: yaml:"format"
	Format Format `protobuf:"varint,1,opt,name=format,proto3,enum=zlog.Format" json:"format,omitempty" yaml:"format"`
	// @gotags: yaml:"file_name"
	FileName string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty" yaml:"file_name"`
	// @gotags: yaml:"max_file"
	MaxFile int32 `protobuf:"varint,3,opt,name=max_file,json=maxFile,proto3" json:"max_file,omitempty" yaml:"max_file"`
	// @gotags: yaml:"caller_enable"
	CallerEnable bool `protobuf:"varint,4,opt,name=caller_enable,json=callerEnable,proto3" json:"caller_enable,omitempty" yaml:"caller_enable"`
	// @gotags: yaml:"caller_skip"
	CallerSkip int32 `protobuf:"varint,5,opt,name=caller_skip,json=callerSkip,proto3" json:"caller_skip,omitempty" yaml:"caller_skip"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zlog_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_zlog_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_zlog_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetFormat() Format {
	if x != nil {
		return x.Format
	}
	return Format_UNKNOWN
}

func (x *Config) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Config) GetMaxFile() int32 {
	if x != nil {
		return x.MaxFile
	}
	return 0
}

func (x *Config) GetCallerEnable() bool {
	if x != nil {
		return x.CallerEnable
	}
	return false
}

func (x *Config) GetCallerSkip() int32 {
	if x != nil {
		return x.CallerSkip
	}
	return 0
}

var File_zlog_config_proto protoreflect.FileDescriptor

var file_zlog_config_proto_rawDesc = []byte{
	0x0a, 0x11, 0x7a, 0x6c, 0x6f, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x7a, 0x6c, 0x6f, 0x67, 0x22, 0xac, 0x01, 0x0a, 0x06, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x24, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x7a, 0x6c, 0x6f, 0x67, 0x2e, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x65,
	0x72, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x61,
	0x6c, 0x6c, 0x65, 0x72, 0x53, 0x6b, 0x69, 0x70, 0x2a, 0x2c, 0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e,
	0x53, 0x4f, 0x4c, 0x45, 0x10, 0x02, 0x42, 0x16, 0x5a, 0x14, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6f, 0x68, 0x75, 0x2f, 0x7a, 0x6c, 0x6f, 0x67, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zlog_config_proto_rawDescOnce sync.Once
	file_zlog_config_proto_rawDescData = file_zlog_config_proto_rawDesc
)

func file_zlog_config_proto_rawDescGZIP() []byte {
	file_zlog_config_proto_rawDescOnce.Do(func() {
		file_zlog_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_zlog_config_proto_rawDescData)
	})
	return file_zlog_config_proto_rawDescData
}

var file_zlog_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_zlog_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_zlog_config_proto_goTypes = []any{
	(Format)(0),    // 0: zlog.Format
	(*Config)(nil), // 1: zlog.Config
}
var file_zlog_config_proto_depIdxs = []int32{
	0, // 0: zlog.Config.format:type_name -> zlog.Format
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_zlog_config_proto_init() }
func file_zlog_config_proto_init() {
	if File_zlog_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zlog_config_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zlog_config_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zlog_config_proto_goTypes,
		DependencyIndexes: file_zlog_config_proto_depIdxs,
		EnumInfos:         file_zlog_config_proto_enumTypes,
		MessageInfos:      file_zlog_config_proto_msgTypes,
	}.Build()
	File_zlog_config_proto = out.File
	file_zlog_config_proto_rawDesc = nil
	file_zlog_config_proto_goTypes = nil
	file_zlog_config_proto_depIdxs = nil
}
